# Generated by Django 4.2.3 on 2023-07-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete_info',
            name='id_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='id_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
