# Generated by Django 4.2.2 on 2023-08-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdss', '0002_complete_info_id_user_schedule_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
